language: rust
matrix:
  fast_finish: true
  include:
  - rust: nightly
  - rust: beta
  - rust: stable
script:
- cargo build
- cargo test
- cargo bench
- cargo doc
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
  - secure: R7WfOm1U6XVe1YzHX+V5NCqe6qXQs5aJNJUND4VqVStK2S2QvFfTKvGTNWkoVHCL2b78KGZiwqtlKzFa2DnsV2mH2eWCnOmUh+E3DqwZ89CVY1jwSJcZhuodDiaSHQ0qW8YmFrLhsrzMcpQ0iLXRns5x8vdC3r34Wl21b89zE0zpPtLqWbjrDzy71C3miftZpqfR63pqkmaeu2A3RPhojHoTjqEZ1a84x8L0fPjLD1dxX0n7hxt0SLLIBUJXxrcoY/WN/egUl/BRBiMc2wMh/zFIOOTUvCO4ByjHcQqG3FkWpHpSd3c2ud7bKc5r4j75236kErC2vRdGsWGP5csGz3Zm9lPE2HRfi1P9b+qskhwKwXE2td3XzCDdNkWVbiW1RRlA6z1nsDApsNcAkl0HCD2E1D40NoLrpknyk5E3Le6vdYVeffdsvhnzK2WwMznR0nA3GPRCQKEt2owK0Tn/lQXmI1fScRzsltY9tpjx2v5FZMDVcNDGPoDOJcw1k/n3HrhOKpixn1PlDFsDO41E/5qoojA8HEU7Ua5LvLlXhOOhZXLZV3yV2RlGsIUiYDNWmDc0oiWHchrCVPU6rdHwNtafJJQEoYtJrogNkcqWT2mdWKJIhFQFyutIzkwZS9Vga9p9cMqb5Slm82RmEO33VOE5TpifZrDTuSVa5YU0HRw=
  - secure: d0zl22vgMQ5bmkDbPEXF9pzLMxkcemCfNKZ0UgyTKt/Q8sMgPzJHwKQE1dIQ0bwSkT6OgOIsjzZ6KvneB2T7B9uzaTN1XQ83N6TM2e+OtscQRdcBr4e+BazdAonDrneseLJr3PxX88Y0ivy1DhkxpWJXk5EBi1kIVFyoo0Yn4qXYlD4JYWzEs15hzeyaeGY95dy2Frc/9LcCc3+Fp6zqF7X3cGyHy0GEBWVnVRES5nICCTympQhiQUUsW2F0L+0XA55NNAs80GXTm4lAqjxpQH3zeuek51r0HWNa+w7NzXVObXZirpd+uyY4qn3EnT7xpi/Pwihfk+LKKJSEbhbevpbTXrP4DIu4AJudZRhpw6ErfZSglLi0nPWL4wOMnFfzdDkvTtkV83bC4f/P9tUE2Fnc7/QBOgrIYiB5XWuhkKVMmVfdFX2C2fKz42chsJujdxtffVCpb5i69OsomQkBUkli9uwRXSfU02ky6dqWTM/0S3aaL2+3C29wDjGMVsigOJniHD0kmaAFFieI9ga3C35rcT7IhKN+u4kSbVjlz7MSKXqb6r+CJnTDmQFKIPDr1XCep4tO/3ZLLUaVYyHRANUULpjIRal82+CDpTcxe8lU1vR06MB63XeTH4GOGtc4n85sdmtdu67tir06blkCrcxNhFnXNEVja7eW6XSjd/w=
  - secure: OhGVaFoDbiTjMzQM4vRuD3lcvfWKgYEbAP2Ol3cP7PwniOQd4I98DpF5SnBk4Mj9nkgsewU1yYmRqaxSrNhDFih3QhtLXKgljO4bqxHYN6wDFHEqmr8QtHiOFYPjcNwsd8Dnwx4pzNtloay1ot9LjzLvc5jqB1DQsyzpHvFgtTJJo5QZqBdrk85dEYXWMPiyA+Us8TQu0st0QY5IG0D2iiWhg5tKBTvLP2wMntkjFCQVO40Xt6OAVbeUL7Cr9DYL2zvvqaUknFtla9OwAuf3Gz+xSTFpWIJ6+LQShe2xotZ7qu2+yL+HTgzBNfuhQamhpNy1TQ5gS46vChQecSf1QxGGqKsaxWyLzTpBGcVIhdPTJFmsmG9V4z13h0xFj3/rWDVqbm5HnaWNQlPAcl0/xCteNUgF85ZNvVYJMv7MGF12YuhvBghgV6ERH5l0ZPrbBkntVfrSbGq4XWDIwER69x2NjWN2T+z2EW0iUKxHWxwOKQk6Jhk/2lzCmz1mvBBs15iaQ/+aDF23f06QIrReqAo1NZ3+v64o7SHYY3Sjdy+4+hcyDLFfb1zb8ulOnFpHg+tHqeAdn3U0psuK4pUOZN5/+pFOn2uFJGQ8h0q/3Y+sWKlXWkuRIM5PlhXQwbfdnObDXDNqvsGarozJZ1BEZXap/WbWz2Ja7VSUfIxYV7k=
